/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InfinitaTreehouseRouteImport } from './routes/infinita-treehouse'
import { Route as IndexRouteImport } from './routes/index'

const InfinitaTreehouseRoute = InfinitaTreehouseRouteImport.update({
  id: '/infinita-treehouse',
  path: '/infinita-treehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/infinita-treehouse': typeof InfinitaTreehouseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/infinita-treehouse': typeof InfinitaTreehouseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/infinita-treehouse': typeof InfinitaTreehouseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/infinita-treehouse'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/infinita-treehouse'
  id: '__root__' | '/' | '/infinita-treehouse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InfinitaTreehouseRoute: typeof InfinitaTreehouseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/infinita-treehouse': {
      id: '/infinita-treehouse'
      path: '/infinita-treehouse'
      fullPath: '/infinita-treehouse'
      preLoaderRoute: typeof InfinitaTreehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InfinitaTreehouseRoute: InfinitaTreehouseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
