/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegiaoSantaCatarinaRouteImport } from './routes/regiao-santa-catarina'
import { Route as MonolytRouteImport } from './routes/monolyt'
import { Route as InfinitaTreehouseRouteImport } from './routes/infinita-treehouse'
import { Route as BlueHeavenRouteImport } from './routes/blue-heaven'
import { Route as AquosOasisHomeRouteImport } from './routes/aquos-oasis-home'
import { Route as IndexRouteImport } from './routes/index'

const RegiaoSantaCatarinaRoute = RegiaoSantaCatarinaRouteImport.update({
  id: '/regiao-santa-catarina',
  path: '/regiao-santa-catarina',
  getParentRoute: () => rootRouteImport,
} as any)
const MonolytRoute = MonolytRouteImport.update({
  id: '/monolyt',
  path: '/monolyt',
  getParentRoute: () => rootRouteImport,
} as any)
const InfinitaTreehouseRoute = InfinitaTreehouseRouteImport.update({
  id: '/infinita-treehouse',
  path: '/infinita-treehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueHeavenRoute = BlueHeavenRouteImport.update({
  id: '/blue-heaven',
  path: '/blue-heaven',
  getParentRoute: () => rootRouteImport,
} as any)
const AquosOasisHomeRoute = AquosOasisHomeRouteImport.update({
  id: '/aquos-oasis-home',
  path: '/aquos-oasis-home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aquos-oasis-home': typeof AquosOasisHomeRoute
  '/blue-heaven': typeof BlueHeavenRoute
  '/infinita-treehouse': typeof InfinitaTreehouseRoute
  '/monolyt': typeof MonolytRoute
  '/regiao-santa-catarina': typeof RegiaoSantaCatarinaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aquos-oasis-home': typeof AquosOasisHomeRoute
  '/blue-heaven': typeof BlueHeavenRoute
  '/infinita-treehouse': typeof InfinitaTreehouseRoute
  '/monolyt': typeof MonolytRoute
  '/regiao-santa-catarina': typeof RegiaoSantaCatarinaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aquos-oasis-home': typeof AquosOasisHomeRoute
  '/blue-heaven': typeof BlueHeavenRoute
  '/infinita-treehouse': typeof InfinitaTreehouseRoute
  '/monolyt': typeof MonolytRoute
  '/regiao-santa-catarina': typeof RegiaoSantaCatarinaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aquos-oasis-home'
    | '/blue-heaven'
    | '/infinita-treehouse'
    | '/monolyt'
    | '/regiao-santa-catarina'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aquos-oasis-home'
    | '/blue-heaven'
    | '/infinita-treehouse'
    | '/monolyt'
    | '/regiao-santa-catarina'
  id:
    | '__root__'
    | '/'
    | '/aquos-oasis-home'
    | '/blue-heaven'
    | '/infinita-treehouse'
    | '/monolyt'
    | '/regiao-santa-catarina'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AquosOasisHomeRoute: typeof AquosOasisHomeRoute
  BlueHeavenRoute: typeof BlueHeavenRoute
  InfinitaTreehouseRoute: typeof InfinitaTreehouseRoute
  MonolytRoute: typeof MonolytRoute
  RegiaoSantaCatarinaRoute: typeof RegiaoSantaCatarinaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regiao-santa-catarina': {
      id: '/regiao-santa-catarina'
      path: '/regiao-santa-catarina'
      fullPath: '/regiao-santa-catarina'
      preLoaderRoute: typeof RegiaoSantaCatarinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monolyt': {
      id: '/monolyt'
      path: '/monolyt'
      fullPath: '/monolyt'
      preLoaderRoute: typeof MonolytRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infinita-treehouse': {
      id: '/infinita-treehouse'
      path: '/infinita-treehouse'
      fullPath: '/infinita-treehouse'
      preLoaderRoute: typeof InfinitaTreehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blue-heaven': {
      id: '/blue-heaven'
      path: '/blue-heaven'
      fullPath: '/blue-heaven'
      preLoaderRoute: typeof BlueHeavenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aquos-oasis-home': {
      id: '/aquos-oasis-home'
      path: '/aquos-oasis-home'
      fullPath: '/aquos-oasis-home'
      preLoaderRoute: typeof AquosOasisHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AquosOasisHomeRoute: AquosOasisHomeRoute,
  BlueHeavenRoute: BlueHeavenRoute,
  InfinitaTreehouseRoute: InfinitaTreehouseRoute,
  MonolytRoute: MonolytRoute,
  RegiaoSantaCatarinaRoute: RegiaoSantaCatarinaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
